Update Script

diff --git a/Modulos/apache2menu b/Modulos/apache2menu
--- a/Modulos/apache2menu
+++ b/Modulos/apache2menu
@@ -1,5 +1,5 @@
 #!/bin/bash
-# MENU APACHE V3.5 
+# MEN� APACHE V3.5
 IP=$(cat /etc/IP)
 x="ok"
 
@@ -34,7 +34,7 @@ gestorapache2 ()
 {
 port () {
 local portas
-local portas_var=$(lsof -V -i tcp -P -n | grep -v "ESTABELECIDO" |grep -v "COMANDO" | grep "LISTEN")
+local portas_var=$(lsof -V -i tcp -P -n | grep -v "ESTABLECIDO" |grep -v "COMANDO" | grep "LISTEN")
 i=0
 while read port; do
 var1=$(echo $port | awk '{print $1}') && var2=$(echo $port | awk '{print $9}' | awk -F ":" '{print $2}')
@@ -66,7 +66,7 @@ echo ""
 echo -e "\033[01;32m APACHE2 INSTALADO!"
 echo ""
 sleep 2s
-conexao
+conexion
 exit
 }
 
@@ -85,21 +85,21 @@ echo -e "\033[01;32m APACHE2 DESINSTALADO!"
 [[ -d /etc/apache2 ]] && rm -rf /etc/apache2
 echo ""
 sleep 2s
-conexao
+conexion
 exit
 }
 
 edit_apache () {
 clear
-echo -e "\033[01;32mREDEFINIR PORTA APACHE2 "
+echo -e "\033[01;32mREDEFINIR PUERTO APACHE2 "
 echo ""
 local CONF="/etc/apache2/ports.conf"
 local NEWCONF="$(cat ${CONF})"
-echo -ne "\033[01;37mNova Porta: "
+echo -ne "\033[01;37mNuevo Puerto: "
 read -p "" newports
 for PTS in `echo ${newports}`; do
-verify_port apache "${PTS}" && echo -e "\033[1;33mPort $PTS \033[1;32mOK" || {
-echo -e "\033[1;33mPort $PTS \033[1;31mFALHOU"
+verify_port apache "${PTS}" && echo -e "\033[1;33mPuerto $PTS \033[1;32mOK" || {
+echo -e "\033[1;33mPuerto $PTS \033[1;31mFALL�"
 service apache2 restart &>/dev/null
 echo ""
 sleep 2s
@@ -120,11 +120,11 @@ else
 echo -e "${varline}" >> ${CONF}
 fi
 done <<< "${NEWCONF}"
-echo -e "\033[01;36mAGUARDE"
+echo -e "\033[01;36mESPERA"
 service apache2 restart &>/dev/null
 sleep 1s
 echo ""
-echo -e "\033[1;32m PORTA REDEFINIDA"
+echo -e "\033[1;32m PUERTO REDEFINIDO"
 echo ""
 sleep 2s
 gestorapache2
@@ -151,7 +151,7 @@ service apache2 start > /dev/null 2>&1
 fun_bar "service apache2 restart"
 rm -rf /etc/apache2/apache_stop
 echo ""
-echo -e "\033[1;32m APACHE ATIVADO!"
+echo -e "\033[1;32m APACHE ACTIVADO!"
 echo ""
 sleep 2s
 gestorapache2
@@ -181,18 +181,18 @@ exit
 }
 
 mine_port () {
-local portasVAR=$(lsof -V -i tcp -P -n | grep -v "ESTABELECIDO" |grep -v "COMANDO" | grep "LISTEN")
+local portasVAR=$(lsof -V -i tcp -P -n | grep -v "ESTABLECIDO" | grep -v "COMANDO" | grep "LISTEN")
 local NOREPEAT
 local reQ
 local Port
 while read port; do
-reQ=$(echo ${port}|awk '{print $1}')
-Port=$(echo {$port} | awk '{print $9}' | awk -F ":" '{print $2}')
+reQ=$(echo ${port} | awk '{print $1}')
+Port=$(echo ${port} | awk '{print $9}' | awk -F ":" '{print $2}')
 [[ $(echo -e $NOREPEAT|grep -w "$Port") ]] && continue
 NOREPEAT+="$Port\n"
 case ${reQ} in
 apache|apache2)
-[[ -z $APC ]] && echo "" && local APC="\033[1;33mPORTA\033[1;37m: \033[1;32m"
+[[ -z $APC ]] && echo "" && local APC="\033[1;33mPUERTO\033[1;37m: \033[1;32m"
 APC+="$Port ";;
 esac
 done <<< "${portasVAR}"
@@ -208,17 +208,17 @@ fi
 clear
 unset OPENBAR
 [[ $(port|grep -w "apache2") ]] && OPENBAR="\033[1;32m◉ " || OPENBAR="\033[1;31m○ "
-echo -e "\E[44;1;37m               GERENCIAR APACHE2                  \E[0m"
+echo -e "\E[44;1;37m               GESTIONAR APACHE2                  \E[0m"
 mine_port
 echo ""
 echo -e "\033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;33mDESINSTALAR APACHE2 "   
-echo -e "\033[1;31m[\033[1;36m02\033[1;31m] \033[1;37m• \033[1;33mREDEFINIR PORTA "
-echo -e "\033[1;31m[\033[1;36m03\033[1;31m] \033[1;37m• \033[1;33mEDITAR CLIENTE \033[1;31m(comand nano) "                   
-echo -e "\033[1;31m[\033[1;36m04\033[1;31m] \033[1;37m• \033[1;33mINICIAR OU PARAR $OPENBAR "
+echo -e "\033[1;31m[\033[1;36m02\033[1;31m] \033[1;37m• \033[1;33mREDEFINIR PUERTO "
+echo -e "\033[1;31m[\033[1;36m03\033[1;31m] \033[1;37m• \033[1;33mEDITAR CLIENTE \033[1;31m(comando nano) "                   
+echo -e "\033[1;31m[\033[1;36m04\033[1;31m] \033[1;37m• \033[1;33mINICIAR O DETENER $OPENBAR "
 echo -e "\033[1;31m[\033[1;36m05\033[1;31m] \033[1;37m• \033[1;33mINDEX NOT FOUND 404 "
-echo -e "\033[1;31m[\033[1;36m00\033[1;31m] \033[1;37m• \033[1;33mVOLTA AO MENU \033[1;32m<\033[1;33m<\033[1;31m< "
+echo -e "\033[1;31m[\033[1;36m00\033[1;31m] \033[1;37m• \033[1;33mVOLVER AL MENU \033[1;32m<\033[1;33m<\033[1;31m< "
 echo ""
-echo -ne "\033[1;32mOPCAO \033[1;33m?\033[1;31m?\033[1;37m : "; read x
+echo -ne "\033[1;32mOPCION \033[1;33m?\033[1;31m?\033[1;37m : "; read x
 
 case "$x" in 
    1 | 01)
@@ -247,10 +247,10 @@ case "$x" in
    exit;
    ;;
    *)
-   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
+   echo -e "\n\033[1;31mOpcion invalida !\033[0m"
    sleep 1
 esac
 done
 }
 gestorapache2
-#fim
+#fin
