Update Script

diff --git a/Modulos/atualizarsistema b/Modulos/atualizarsistema
--- a/Modulos/atualizarsistema
+++ b/Modulos/atualizarsistema
@@ -1,5 +1,6 @@
 #!/bin/bash
 clear
+
 fun_prog ()
 {
 	comando[0]="$1" 
@@ -17,21 +18,20 @@ fun_prog ()
 	tput cnorm
 	echo -e "\e[1DOK"
 }
-echo -ne "\033[1;33mAPLICANDO UPDATE"; fun_prog 'apt-get update -y'
-apt-get update -y > /dev/null 2>&1
+
+echo -ne "\033[1;33mAPLICANDO UPDATE\033[1;32m.\033[1;33m.\033[1;31m."
+apt-get update -y > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
 echo ""
+echo -ne "\033[1;32mQuieres continuar con la upgrade?"; read -p " [Y/n]: " PROS
+[[ $PROS = @(y|Y|s|S) ]] || exit 0
+tput cuu1 && tput dl1
+echo -ne "\033[1;33mAPLICANDO UPGRADE\033[1;32m.\033[1;33m.\033[1;31m."
+apt-get upgrade -y > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
 sleep 1
-echo -ne "\033[1;33mAPLICANDO UPGRADE"; fun_prog 'apt-get upgrade -y'
-apt-get upgrade -y > /dev/null 2>&1
-echo ""
-sleep 1
-# echo -ne "\033[1;33mAPLICANDO DIST-UPGRADE"; fun_prog 'apt-get dist-upgrade -y'
-# apt-get update -y > /dev/null 2>&1
+# echo -ne "\033[1;33mAPLICANDO DIST-UPGRADE\033[1;32m.\033[1;33m.\033[1;31m."
+# dist-upgrade -y > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
 # echo ""
-# sleep 1
-# echo -ne "\033[1;33mAPLICANDO FULL-UPGRADE"; fun_prog 'apt-get full-upgrade -y'
-# apt-get update -y > /dev/null 2>&1
+# echo -ne "\033[1;33mAPLICANDO FULL-UPGRADE\033[1;32m.\033[1;33m.\033[1;31m."
+# apt-get full-upgrade -y > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
 # echo ""
-# sleep 1
 # echo -e "\033[1;32mACTUALIZACION EXITOSA DEL SISTEMA!\033[0m"
-# sleep 1
