Update Script

diff --git a/Modulos/botssh b/Modulos/botssh
--- a/Modulos/botssh
+++ b/Modulos/botssh
@@ -1,9 +1,9 @@
 #!/bin/bash
 #====================================================
-#	SCRIPT: BOTSSH SSHPLUS MANAGER
+#	SCRIPT: BOTSSH ADMPLUS-MANAGER-PRO MANAGER
 #	DESENVOLVIDO POR:	CRAZY_VPN
 #	CONTATO TELEGRAM:	http://t.me/crazy_vpn
-#	CANAL TELEGRAM:	http://t.me/sshplus
+#	CANAL TELEGRAM:	http://t.me/ADMPLUS-MANAGER-PRO
 #====================================================
 clear
 [[ $(awk -F" " '{print $2}' /usr/lib/licence) != "@CRAZY_VPN" ]] && exit 0
@@ -37,25 +37,25 @@ fun_bar() {
 fun_botOnOff() {
     [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) = '0' ]] && {
         clear
-        echo -e "\E[44;1;37m             INSTALADOR BOT SSHPLUS                \E[0m\n"
-        echo -ne "\033[1;32mINFORME SEU TOKEN:\033[1;37m "
+        echo -e "\E[44;1;37m             INSTALADOR BOT ADMPLUS-MANAGER-PRO                \E[0m\n"
+        echo -ne "\033[1;32mINFORME SU TOKEN:\033[1;37m "
         read tokenbot
         echo ""
-        echo -ne "\033[1;32mINFORME SEU ID:\033[1;37m "
+        echo -ne "\033[1;32mINFORME SU ID:\033[1;37m "
         read iduser
         clear
-        echo -e "\033[1;32mINICIANDO BOT SSHPLUS \033[0m\n"
+        echo -e "\033[1;32mINICIANDO BOT ADMPLUS-MANAGER-PRO \033[0m\n"
         fun_bot1() {
-            [[ ! -e "/etc/SSHPlus/ShellBot.sh" ]] && {
-				wget -qO- https://raw.githubusercontent.com/shellscriptx/shellbot/master/ShellBot.sh >/etc/SSHPlus/ShellBot.sh
+            [[ ! -e "/etc/ADMPLUS-MANAGER-PRO/ShellBot.sh" ]] && {
+				wget -qO- https://raw.githubusercontent.com/shellscriptx/shellbot/main/ShellBot.sh >/etc/ADMPLUS-MANAGER-PRO/ShellBot.sh
 			}
-            cd /etc/SSHPlus
+            cd /etc/ADMPLUS-MANAGER-PRO
             screen -dmS bot_plus ./bot $tokenbot $iduser >/dev/null 2>&1
             [[ $(grep -wc "bot_plus" /etc/autostart) = '0' ]] && {
-                echo -e "ps x | grep 'bot_plus' | grep -v 'grep' || cd /etc/SSHPlus && screen -dmS bot_plus ./bot $tokenbot $iduser && cd $HOME" >>/etc/autostart
+                echo -e "ps x | grep 'bot_plus' | grep -v 'grep' || cd /etc/ADMPLUS-MANAGER-PRO && screen -dmS bot_plus ./bot $tokenbot $iduser && cd $HOME" >>/etc/autostart
             } || {
                 sed -i '/bot_plus/d' /etc/autostart
-                echo -e "ps x | grep 'bot_plus' | grep -v 'grep' || cd /etc/SSHPlus && screen -dmS bot_plus ./bot $tokenbot $iduser && cd $HOME" >>/etc/autostart
+                echo -e "ps x | grep 'bot_plus' | grep -v 'grep' || cd /etc/ADMPLUS-MANAGER-PRO && screen -dmS bot_plus ./bot $tokenbot $iduser && cd $HOME" >>/etc/autostart
             }
             [[ $(crontab -l | grep -c "verifbot") = '0' ]] && (
                 crontab -l 2>/dev/null
@@ -64,12 +64,12 @@ fun_botOnOff() {
             cd $HOME
         }
         fun_bar 'fun_bot1'
-        [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m BOT SSHPLUS ATIVADO !\033[0m" || echo -e "\n\033[1;31m ERRO! REANALISE SUAS INFORMACOES\033[0m"
+        [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m BOT ADMPLUS-MANAGER-PRO ACTIVADO !\033[0m" || echo -e "\n\033[1;31m ERROR! VUELVA A ANALIZAR SU INFORMACIÓN\033[0m"
         sleep 2
         menu
     } || {
         clear
-        echo -e "\033[1;32mPARANDO BOT SSHPLUS... \033[0m\n"
+        echo -e "\033[1;32mPARANDO BOT ADMPLUS-MANAGER-PRO... \033[0m\n"
         fun_bot2() {
             screen -r -S "bot_plus" -X quit
             screen -wipe 1>/dev/null 2>/dev/null
@@ -80,21 +80,21 @@ fun_botOnOff() {
             sleep 1
         }
         fun_bar 'fun_bot2'
-        echo -e "\n\033[1;32m \033[1;31mBOT SSHPLUS PARADO! \033[0m"
+        echo -e "\n\033[1;32m \033[1;31mBOT ADMPLUS-MANAGER-PRO PARADO! \033[0m"
         sleep 2
         menu
     }
 }
 
 fun_instbot() {
-    echo -e "\E[44;1;37m             INSTALADOR BOT SSHPLUS                \E[0m\n"
-    echo -e "                 \033[1;33m[\033[1;31m!\033[1;33m] \033[1;31mATENCAO \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
-    echo -e "\n\033[1;32m1° \033[1;37m- \033[1;33mPELO SEU TELEGRAM ACESSE OS SEGUINTES BOT\033[1;37m:\033[0m"
-    echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;33mCRIE O SEU BOT \033[1;31mOPCAO: \033[1;37m/newbot\033[0m"
-    echo -e "\n\033[1;32m3° \033[1;37m- \033[1;33mBOT \033[1;37m@SSHPLUS_BOT \033[1;33mE PEGUE SEU ID \033[1;31mOPCAO: \033[1;37m/id\033[0m"
+    echo -e "\E[44;1;37m             INSTALADOR BOT ADMPLUS-MANAGER-PRO                \E[0m\n"
+    echo -e "                 \033[1;33m[\033[1;31m!\033[1;33m] \033[1;31m¡ATENCIÓN \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
+    echo -e "\n\033[1;32m1° \033[1;37m- \033[1;33mEN TU TELEGRAM ACCEDE AL SIGUIENTE BOT\033[1;37m:\033[0m"
+    echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;33mCREA TU BOT \033[1;31mOPCION: \033[1;37m/newbot\033[0m"
+    echo -e "\n\033[1;32m3° \033[1;37m- \033[1;33mBOT \033[1;37m@ADMPLUS-MANAGER-PRO_BOT \033[1;33mY PEGUE SU ID \033[1;31mOPCION: \033[1;37m/id\033[0m"
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[1;32m"
     echo ""
-    read -p "DESEJA CONTINUAR ? [s/n]: " -e -i s resposta
+    read -p "DESEA CONTINUAR ? [s/n]: " -e -i s resposta
     [[ "$resposta" = 's' ]] && {
         fun_botOnOff
     } || {
@@ -103,5 +103,5 @@ fun_instbot() {
         menu
     }
 }
-[[ -f "/etc/SSHPlus/ShellBot.sh" ]] && fun_botOnOff || fun_instbot
+[[ -f "/etc/ADMPLUS-MANAGER-PRO/ShellBot.sh" ]] && fun_botOnOff || fun_instbot
 #fim
